/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'date' : string,
  'blockId' : [] | [string],
  'unit' : string,
  'description' : string,
  'projectId' : string,
  'includesGst' : boolean,
  'billNumber' : string,
  'quantity' : number,
  'unitPrice' : number,
  'amount' : number,
  'remarks' : [] | [string],
}
export interface BillFilters {
  'maxAmount' : [] | [number],
  'client' : [] | [string],
  'minAmount' : [] | [number],
  'blockId' : [] | [string],
  'search' : [] | [string],
  'toDate' : [] | [string],
  'projectId' : [] | [string],
  'fromDate' : [] | [string],
  'includesGst' : [] | [boolean],
  'billNumber' : [] | [string],
}
export interface BillKey { 'projectId' : string, 'billNumber' : string }
export interface Client {
  'id' : string,
  'contact' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
}
export interface DashboardMetrics {
  'outstanding' : number,
  'totalPayments' : number,
  'totalGst' : number,
  'totalBills' : number,
}
export interface Payment {
  'id' : string,
  'date' : string,
  'reference' : string,
  'projectId' : string,
  'paymentMode' : PaymentMode,
  'amount' : number,
  'remarks' : [] | [string],
}
export interface PaymentFilters {
  'maxAmount' : [] | [number],
  'minAmount' : [] | [number],
  'reference' : [] | [string],
  'search' : [] | [string],
  'toDate' : [] | [string],
  'projectId' : [] | [string],
  'fromDate' : [] | [string],
  'paymentMode' : [] | [PaymentMode],
}
export type PaymentMode = { 'cash' : null } |
  { 'account' : null };
export interface Project {
  'id' : string,
  'client' : string,
  'endDate' : string,
  'name' : string,
  'address' : string,
  'notes' : string,
  'quantity' : number,
  'contactNumber' : string,
  'unitPrice' : number,
  'attachmentLinks' : Array<string>,
  'location' : string,
  'estimatedAmount' : number,
  'startDate' : string,
}
export interface ProjectAnalyticsData {
  'id' : string,
  'name' : string,
  'outstandingAmount' : number,
}
export interface ProjectFilters {
  'client' : [] | [string],
  'maxUnitPrice' : [] | [number],
  'search' : [] | [string],
  'toDate' : [] | [string],
  'fromDate' : [] | [string],
  'minUnitPrice' : [] | [number],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserFilters {
  'contact' : [] | [string],
  'name' : [] | [string],
  'role' : [] | [UserRole],
  'email' : [] | [string],
}
export interface UserProfile {
  'active' : boolean,
  'contact' : string,
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addBill' : ActorMethod<[Bill], undefined>,
  'addClient' : ActorMethod<[Client], undefined>,
  'addPayment' : ActorMethod<[Payment], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addUser' : ActorMethod<[Principal, UserProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeleteBillsWithPassword' : ActorMethod<
    [string, Array<BillKey>],
    undefined
  >,
  'bulkDeleteClients' : ActorMethod<[string], undefined>,
  'bulkDeletePayments' : ActorMethod<[string, Array<string>], undefined>,
  'bulkDeleteProjects' : ActorMethod<[string], undefined>,
  'deleteBill' : ActorMethod<[string, string], undefined>,
  'deleteClient' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal, string], undefined>,
  'filterBills' : ActorMethod<[BillFilters], Array<Bill>>,
  'filterBillsByProject' : ActorMethod<[string], Array<Bill>>,
  'filterPayments' : ActorMethod<[PaymentFilters], Array<Payment>>,
  'filterProjects' : ActorMethod<[ProjectFilters], Array<Project>>,
  'filterUsers' : ActorMethod<[UserFilters], Array<[Principal, UserProfile]>>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProjectNames' : ActorMethod<[], Array<string>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getGreetingMessage' : ActorMethod<[null], string>,
  'getOutstandingAmount' : ActorMethod<[], number>,
  'getProjectSummary' : ActorMethod<
    [string],
    [] | [
      {
        'outstanding' : number,
        'accountPayments' : number,
        'cashPayments' : number,
        'totalPayments' : number,
        'gstOutstanding' : number,
        'totalBills' : number,
        'project' : Project,
      }
    ]
  >,
  'getProjectWiseAnalyticsData' : ActorMethod<
    [string],
    Array<ProjectAnalyticsData>
  >,
  'getSortedBills' : ActorMethod<[[] | [string], boolean], Array<Bill>>,
  'getTotalGst' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasActiveProfile' : ActorMethod<[string], boolean>,
  'hasProfileSetup' : ActorMethod<[], boolean>,
  'importActiveUsers' : ActorMethod<
    [Array<[Principal, UserProfile]>],
    undefined
  >,
  'importBills' : ActorMethod<[Array<Bill>], undefined>,
  'importClients' : ActorMethod<[Array<Client>], undefined>,
  'importPayments' : ActorMethod<[Array<Payment>], undefined>,
  'importProjects' : ActorMethod<[Array<Project>], undefined>,
  'importUsers' : ActorMethod<[Array<[Principal, UserProfile]>], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleUserActiveStatus' : ActorMethod<[Principal, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBill' : ActorMethod<[Bill], undefined>,
  'updateClient' : ActorMethod<[Client], undefined>,
  'updatePayment' : ActorMethod<[Payment], undefined>,
  'updateProject' : ActorMethod<[Project], undefined>,
  'updateUser' : ActorMethod<[Principal, UserProfile], undefined>,
  'validateActiveUser' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];