/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Bill = IDL.Record({
  'date' : IDL.Text,
  'blockId' : IDL.Opt(IDL.Text),
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'projectId' : IDL.Text,
  'includesGst' : IDL.Bool,
  'billNumber' : IDL.Text,
  'quantity' : IDL.Float64,
  'unitPrice' : IDL.Float64,
  'amount' : IDL.Float64,
  'remarks' : IDL.Opt(IDL.Text),
});
export const Client = IDL.Record({
  'id' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
});
export const PaymentMode = IDL.Variant({
  'cash' : IDL.Null,
  'account' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'reference' : IDL.Text,
  'projectId' : IDL.Text,
  'paymentMode' : PaymentMode,
  'amount' : IDL.Float64,
  'remarks' : IDL.Opt(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'client' : IDL.Text,
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Float64,
  'contactNumber' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'attachmentLinks' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'estimatedAmount' : IDL.Float64,
  'startDate' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'active' : IDL.Bool,
  'contact' : IDL.Text,
  'accessProjects' : IDL.Vec(IDL.Text),
  'role' : UserRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const BillKey = IDL.Record({
  'projectId' : IDL.Text,
  'billNumber' : IDL.Text,
});
export const BillFilters = IDL.Record({
  'maxAmount' : IDL.Opt(IDL.Float64),
  'client' : IDL.Opt(IDL.Text),
  'minAmount' : IDL.Opt(IDL.Float64),
  'blockId' : IDL.Opt(IDL.Text),
  'search' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(IDL.Text),
  'projectId' : IDL.Opt(IDL.Text),
  'fromDate' : IDL.Opt(IDL.Text),
  'includesGst' : IDL.Opt(IDL.Bool),
  'billNumber' : IDL.Opt(IDL.Text),
});
export const PaymentFilters = IDL.Record({
  'maxAmount' : IDL.Opt(IDL.Float64),
  'minAmount' : IDL.Opt(IDL.Float64),
  'reference' : IDL.Opt(IDL.Text),
  'search' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(IDL.Text),
  'projectId' : IDL.Opt(IDL.Text),
  'fromDate' : IDL.Opt(IDL.Text),
  'paymentMode' : IDL.Opt(PaymentMode),
});
export const ProjectFilters = IDL.Record({
  'client' : IDL.Opt(IDL.Text),
  'maxUnitPrice' : IDL.Opt(IDL.Float64),
  'search' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(IDL.Text),
  'fromDate' : IDL.Opt(IDL.Text),
  'minUnitPrice' : IDL.Opt(IDL.Float64),
});
export const DashboardMetrics = IDL.Record({
  'outstanding' : IDL.Float64,
  'totalPayments' : IDL.Float64,
  'totalGst' : IDL.Float64,
  'totalBills' : IDL.Float64,
});
export const ProjectAnalyticsData = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'outstandingAmount' : IDL.Float64,
});
export const ImportRequest = IDL.Record({
  'projectsData' : IDL.Vec(Project),
  'billsData' : IDL.Vec(Bill),
  'usersData' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  'paymentsData' : IDL.Vec(Payment),
  'clientsData' : IDL.Vec(Client),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBill' : IDL.Func([Bill], [], []),
  'addClient' : IDL.Func([Client], [], []),
  'addPayment' : IDL.Func([Payment], [], []),
  'addProject' : IDL.Func([Project], [], []),
  'addUser' : IDL.Func([UserProfile], [IDL.Principal], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkDeleteBillsWithPassword' : IDL.Func(
      [IDL.Text, IDL.Vec(BillKey)],
      [],
      [],
    ),
  'bulkDeletePayments' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'changeAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteBill' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteClient' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteUsers' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'filterBills' : IDL.Func([BillFilters], [IDL.Vec(Bill)], ['query']),
  'filterBillsByProject' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
  'filterPayments' : IDL.Func([PaymentFilters], [IDL.Vec(Payment)], ['query']),
  'filterProjects' : IDL.Func([ProjectFilters], [IDL.Vec(Project)], ['query']),
  'getAdminPasswordQuestion' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllProjectNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getBillDetails' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getDefaultAdminProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getGreetingMessage' : IDL.Func([IDL.Null], [IDL.Text], ['query']),
  'getHintQuestion' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getOutstandingAmount' : IDL.Func([], [IDL.Float64], ['query']),
  'getPaymentDetails' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
  'getProjectSummary' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'outstanding' : IDL.Float64,
            'accountPayments' : IDL.Float64,
            'cashPayments' : IDL.Float64,
            'totalPayments' : IDL.Float64,
            'gstOutstanding' : IDL.Float64,
            'totalBills' : IDL.Float64,
            'project' : Project,
          })
        ),
      ],
      ['query'],
    ),
  'getProjectWiseAnalyticsData' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProjectAnalyticsData)],
      ['query'],
    ),
  'getSortedBills' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Vec(Bill)],
      ['query'],
    ),
  'getTotalGst' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserAccess' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasActiveProfile' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'hasProfileSetup' : IDL.Func([], [IDL.Bool], ['query']),
  'importData' : IDL.Func([ImportRequest, IDL.Text], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAdminPasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkMasterAdminPrincipal' : IDL.Func([], [IDL.Bool], []),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'revealAdminPassword' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setHintQuestionAndAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBill' : IDL.Func([Bill, IDL.Text], [], []),
  'updateClient' : IDL.Func([Client, IDL.Text], [], []),
  'updatePayment' : IDL.Func([Payment, IDL.Text], [], []),
  'updateProject' : IDL.Func([Project, IDL.Text], [], []),
  'updateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'validateActiveUser' : IDL.Func([IDL.Text], [], ['query']),
  'verifyHintAnswer' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Bill = IDL.Record({
    'date' : IDL.Text,
    'blockId' : IDL.Opt(IDL.Text),
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'projectId' : IDL.Text,
    'includesGst' : IDL.Bool,
    'billNumber' : IDL.Text,
    'quantity' : IDL.Float64,
    'unitPrice' : IDL.Float64,
    'amount' : IDL.Float64,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const Client = IDL.Record({
    'id' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
  });
  const PaymentMode = IDL.Variant({ 'cash' : IDL.Null, 'account' : IDL.Null });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'reference' : IDL.Text,
    'projectId' : IDL.Text,
    'paymentMode' : PaymentMode,
    'amount' : IDL.Float64,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'client' : IDL.Text,
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Float64,
    'contactNumber' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'attachmentLinks' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'estimatedAmount' : IDL.Float64,
    'startDate' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'active' : IDL.Bool,
    'contact' : IDL.Text,
    'accessProjects' : IDL.Vec(IDL.Text),
    'role' : UserRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const BillKey = IDL.Record({
    'projectId' : IDL.Text,
    'billNumber' : IDL.Text,
  });
  const BillFilters = IDL.Record({
    'maxAmount' : IDL.Opt(IDL.Float64),
    'client' : IDL.Opt(IDL.Text),
    'minAmount' : IDL.Opt(IDL.Float64),
    'blockId' : IDL.Opt(IDL.Text),
    'search' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(IDL.Text),
    'projectId' : IDL.Opt(IDL.Text),
    'fromDate' : IDL.Opt(IDL.Text),
    'includesGst' : IDL.Opt(IDL.Bool),
    'billNumber' : IDL.Opt(IDL.Text),
  });
  const PaymentFilters = IDL.Record({
    'maxAmount' : IDL.Opt(IDL.Float64),
    'minAmount' : IDL.Opt(IDL.Float64),
    'reference' : IDL.Opt(IDL.Text),
    'search' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(IDL.Text),
    'projectId' : IDL.Opt(IDL.Text),
    'fromDate' : IDL.Opt(IDL.Text),
    'paymentMode' : IDL.Opt(PaymentMode),
  });
  const ProjectFilters = IDL.Record({
    'client' : IDL.Opt(IDL.Text),
    'maxUnitPrice' : IDL.Opt(IDL.Float64),
    'search' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(IDL.Text),
    'fromDate' : IDL.Opt(IDL.Text),
    'minUnitPrice' : IDL.Opt(IDL.Float64),
  });
  const DashboardMetrics = IDL.Record({
    'outstanding' : IDL.Float64,
    'totalPayments' : IDL.Float64,
    'totalGst' : IDL.Float64,
    'totalBills' : IDL.Float64,
  });
  const ProjectAnalyticsData = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'outstandingAmount' : IDL.Float64,
  });
  const ImportRequest = IDL.Record({
    'projectsData' : IDL.Vec(Project),
    'billsData' : IDL.Vec(Bill),
    'usersData' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
    'paymentsData' : IDL.Vec(Payment),
    'clientsData' : IDL.Vec(Client),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBill' : IDL.Func([Bill], [], []),
    'addClient' : IDL.Func([Client], [], []),
    'addPayment' : IDL.Func([Payment], [], []),
    'addProject' : IDL.Func([Project], [], []),
    'addUser' : IDL.Func([UserProfile], [IDL.Principal], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkDeleteBillsWithPassword' : IDL.Func(
        [IDL.Text, IDL.Vec(BillKey)],
        [],
        [],
      ),
    'bulkDeletePayments' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'changeAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteBill' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteClient' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteUsers' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'filterBills' : IDL.Func([BillFilters], [IDL.Vec(Bill)], ['query']),
    'filterBillsByProject' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
    'filterPayments' : IDL.Func(
        [PaymentFilters],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'filterProjects' : IDL.Func(
        [ProjectFilters],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getAdminPasswordQuestion' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllProjectNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getBillDetails' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Bill)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getDefaultAdminProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getGreetingMessage' : IDL.Func([IDL.Null], [IDL.Text], ['query']),
    'getHintQuestion' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getOutstandingAmount' : IDL.Func([], [IDL.Float64], ['query']),
    'getPaymentDetails' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
    'getProjectSummary' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'outstanding' : IDL.Float64,
              'accountPayments' : IDL.Float64,
              'cashPayments' : IDL.Float64,
              'totalPayments' : IDL.Float64,
              'gstOutstanding' : IDL.Float64,
              'totalBills' : IDL.Float64,
              'project' : Project,
            })
          ),
        ],
        ['query'],
      ),
    'getProjectWiseAnalyticsData' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProjectAnalyticsData)],
        ['query'],
      ),
    'getSortedBills' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Vec(Bill)],
        ['query'],
      ),
    'getTotalGst' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserAccess' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasActiveProfile' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'hasProfileSetup' : IDL.Func([], [IDL.Bool], ['query']),
    'importData' : IDL.Func([ImportRequest, IDL.Text], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAdminPasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkMasterAdminPrincipal' : IDL.Func([], [IDL.Bool], []),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'revealAdminPassword' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setHintQuestionAndAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBill' : IDL.Func([Bill, IDL.Text], [], []),
    'updateClient' : IDL.Func([Client, IDL.Text], [], []),
    'updatePayment' : IDL.Func([Payment, IDL.Text], [], []),
    'updateProject' : IDL.Func([Project, IDL.Text], [], []),
    'updateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'validateActiveUser' : IDL.Func([IDL.Text], [], ['query']),
    'verifyHintAnswer' : IDL.Func([IDL.Text], [IDL.Text], []),
    'toggleProjectCompleted' : IDL.Func([IDL.Text], [], []),
    'getCompletedProjectIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'setProjectMapLocation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getProjectMapLocations' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };