/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'date' : string,
  'blockId' : [] | [string],
  'unit' : string,
  'description' : string,
  'projectId' : string,
  'includesGst' : boolean,
  'billNumber' : string,
  'quantity' : number,
  'unitPrice' : number,
  'amount' : number,
  'remarks' : [] | [string],
}
export interface BillFilters {
  'maxAmount' : [] | [number],
  'client' : [] | [string],
  'minAmount' : [] | [number],
  'blockId' : [] | [string],
  'search' : [] | [string],
  'toDate' : [] | [string],
  'projectId' : [] | [string],
  'fromDate' : [] | [string],
  'includesGst' : [] | [boolean],
  'billNumber' : [] | [string],
}
export interface BillKey { 'projectId' : string, 'billNumber' : string }
export interface Client {
  'id' : string,
  'contact' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
}
export interface DashboardMetrics {
  'outstanding' : number,
  'totalPayments' : number,
  'totalGst' : number,
  'totalBills' : number,
}
export interface ImportRequest {
  'projectsData' : Array<Project>,
  'billsData' : Array<Bill>,
  'usersData' : Array<[Principal, UserProfile]>,
  'paymentsData' : Array<Payment>,
  'clientsData' : Array<Client>,
}
export interface Payment {
  'id' : string,
  'date' : string,
  'reference' : string,
  'projectId' : string,
  'paymentMode' : PaymentMode,
  'amount' : number,
  'remarks' : [] | [string],
}
export interface PaymentFilters {
  'maxAmount' : [] | [number],
  'minAmount' : [] | [number],
  'reference' : [] | [string],
  'search' : [] | [string],
  'toDate' : [] | [string],
  'projectId' : [] | [string],
  'fromDate' : [] | [string],
  'paymentMode' : [] | [PaymentMode],
}
export type PaymentMode = { 'cash' : null } |
  { 'account' : null };
export interface Project {
  'id' : string,
  'client' : string,
  'endDate' : string,
  'name' : string,
  'address' : string,
  'notes' : string,
  'quantity' : number,
  'contactNumber' : string,
  'unitPrice' : number,
  'attachmentLinks' : Array<string>,
  'location' : string,
  'estimatedAmount' : number,
  'startDate' : string,
}
export interface ProjectAnalyticsData {
  'id' : string,
  'name' : string,
  'outstandingAmount' : number,
}
export interface ProjectFilters {
  'client' : [] | [string],
  'maxUnitPrice' : [] | [number],
  'search' : [] | [string],
  'toDate' : [] | [string],
  'fromDate' : [] | [string],
  'minUnitPrice' : [] | [number],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'active' : boolean,
  'contact' : string,
  'accessProjects' : Array<string>,
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBill' : ActorMethod<[Bill], undefined>,
  'addClient' : ActorMethod<[Client], undefined>,
  'addPayment' : ActorMethod<[Payment], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addUser' : ActorMethod<[UserProfile], Principal>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeleteBillsWithPassword' : ActorMethod<
    [string, Array<BillKey>],
    undefined
  >,
  'bulkDeletePayments' : ActorMethod<[string, Array<string>], undefined>,
  'changeAdminPassword' : ActorMethod<
    [string, string, string, string, string, string],
    boolean
  >,
  'deleteBill' : ActorMethod<[string, string, string], undefined>,
  'deleteClient' : ActorMethod<[string, string], undefined>,
  'deletePayment' : ActorMethod<[string, string], undefined>,
  'deleteProject' : ActorMethod<[string, string], undefined>,
  'deleteUsers' : ActorMethod<[string, Array<string>], undefined>,
  'filterBills' : ActorMethod<[BillFilters], Array<Bill>>,
  'filterBillsByProject' : ActorMethod<[string], Array<Bill>>,
  'filterPayments' : ActorMethod<[PaymentFilters], Array<Payment>>,
  'filterProjects' : ActorMethod<[ProjectFilters], Array<Project>>,
  'getAdminPasswordQuestion' : ActorMethod<[], [] | [string]>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProjectNames' : ActorMethod<[], Array<string>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getBillDetails' : ActorMethod<[string, string], [] | [Bill]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getDefaultAdminProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getGreetingMessage' : ActorMethod<[null], string>,
  'getHintQuestion' : ActorMethod<[], [] | [string]>,
  'getOutstandingAmount' : ActorMethod<[], number>,
  'getPaymentDetails' : ActorMethod<[string], [] | [Payment]>,
  'getProjectSummary' : ActorMethod<
    [string],
    [] | [
      {
        'outstanding' : number,
        'accountPayments' : number,
        'cashPayments' : number,
        'totalPayments' : number,
        'gstOutstanding' : number,
        'totalBills' : number,
        'project' : Project,
      }
    ]
  >,
  'getProjectWiseAnalyticsData' : ActorMethod<
    [string],
    Array<ProjectAnalyticsData>
  >,
  'getSortedBills' : ActorMethod<[[] | [string], boolean], Array<Bill>>,
  'getTotalGst' : ActorMethod<[], number>,
  'getUserAccess' : ActorMethod<[string], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasActiveProfile' : ActorMethod<[string], boolean>,
  'hasProfileSetup' : ActorMethod<[], boolean>,
  'importData' : ActorMethod<[ImportRequest, string], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAdminPasswordSet' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkMasterAdminPrincipal' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'revealAdminPassword' : ActorMethod<[string], [] | [string]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setHintQuestionAndAnswer' : ActorMethod<[string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBill' : ActorMethod<[Bill, string], undefined>,
  'updateClient' : ActorMethod<[Client, string], undefined>,
  'updatePayment' : ActorMethod<[Payment, string], undefined>,
  'updateProject' : ActorMethod<[Project, string], undefined>,
  'updateUser' : ActorMethod<[Principal, UserProfile], undefined>,
  'validateActiveUser' : ActorMethod<[string], undefined>,
  'verifyHintAnswer' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];