/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillKey {
    projectId: string;
    billNumber: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ImportRequest {
    projectsData: Array<Project>;
    billsData: Array<Bill>;
    usersData: Array<[Principal, UserProfile]>;
    paymentsData: Array<Payment>;
    clientsData: Array<Client>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentFilters {
    maxAmount?: number;
    minAmount?: number;
    reference?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    paymentMode?: PaymentMode;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: PaymentMode;
    amount: number;
    remarks?: string;
}
export interface BillFilters {
    maxAmount?: number;
    client?: string;
    minAmount?: number;
    blockId?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    includesGst?: boolean;
    billNumber?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ProjectFilters {
    client?: string;
    maxUnitPrice?: number;
    search?: string;
    toDate?: string;
    fromDate?: string;
    minUnitPrice?: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Bill {
    date: string;
    blockId?: string;
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks?: string;
}
export interface DashboardMetrics {
    outstanding: number;
    totalPayments: number;
    totalGst: number;
    totalBills: number;
}
export interface ProjectAnalyticsData {
    id: string;
    name: string;
    outstandingAmount: number;
}
export interface Project {
    id: string;
    client: string;
    endDate: string;
    name: string;
    address: string;
    notes: string;
    quantity: number;
    contactNumber: string;
    unitPrice: number;
    attachmentLinks: Array<string>;
    location: string;
    mapLocation?: string;
    estimatedAmount: number;
    startDate: string;
}
export interface Client {
    id: string;
    contact: string;
    name: string;
    email: string;
    address: string;
    notes: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    active: boolean;
    contact: string;
    accessProjects: Array<string>;
    role: UserRole;
    fullName: string;
    email: string;
}
export enum PaymentMode {
    cash = "cash",
    account = "account"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBill(bill: Bill): Promise<void>;
    addClient(client: Client): Promise<void>;
    addPayment(payment: Payment): Promise<void>;
    addProject(project: Project): Promise<void>;
    addUser(profile: UserProfile): Promise<Principal>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkDeleteBillsWithPassword(password: string, billKeys: Array<BillKey>): Promise<void>;
    bulkDeletePayments(password: string, ids: Array<string>): Promise<void>;
    changeAdminPassword(adminEmail: string, oldPwd: string, newPwd: string, confirmPwd: string, newQuestion: string, newAnswer: string): Promise<boolean>;
    deleteBill(projectId: string, billNumber: string, password: string): Promise<void>;
    deleteClient(id: string, password: string): Promise<void>;
    deletePayment(id: string, password: string): Promise<void>;
    deleteProject(id: string, password: string): Promise<void>;
    deleteUsers(password: string, principalIds: Array<string>): Promise<void>;
    filterBills(billFilters: BillFilters): Promise<Array<Bill>>;
    filterBillsByProject(projectId: string): Promise<Array<Bill>>;
    filterPayments(filters: PaymentFilters): Promise<Array<Payment>>;
    filterProjects(filters: ProjectFilters): Promise<Array<Project>>;
    getAdminPasswordQuestion(): Promise<string | null>;
    getAllBills(): Promise<Array<Bill>>;
    getAllClients(): Promise<Array<Client>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllProjectNames(): Promise<Array<string>>;
    getAllProjects(): Promise<Array<Project>>;
    getBillDetails(projectId: string, billNumber: string): Promise<Bill | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getCompletedProjectIds(): Promise<Array<string>>;
    getDefaultAdminProfile(): Promise<UserProfile | null>;
    getGreetingMessage(arg0: null): Promise<string>;
    getHintQuestion(): Promise<string | null>;
    getOutstandingAmount(): Promise<number>;
    getPaymentDetails(paymentId: string): Promise<Payment | null>;
    getProjectSummary(projectId: string): Promise<{
        outstanding: number;
        accountPayments: number;
        cashPayments: number;
        totalPayments: number;
        gstOutstanding: number;
        totalBills: number;
        project: Project;
    } | null>;
    getProjectWiseAnalyticsData(sortBy: string): Promise<Array<ProjectAnalyticsData>>;
    getSortedBills(sortBy: string | null, ascending: boolean): Promise<Array<Bill>>;
    getTotalGst(): Promise<number>;
    getUserAccess(email: string): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasActiveProfile(email: string): Promise<boolean>;
    hasProfileSetup(): Promise<boolean>;
    importData(request: ImportRequest, password: string): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isAdminPasswordSet(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    linkMasterAdminPrincipal(): Promise<boolean>;
    linkUserByEmail(email: string): Promise<boolean>;
    listUsers(): Promise<Array<[Principal, UserProfile]>>;
    revealAdminPassword(answer: string): Promise<string | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setHintQuestionAndAnswer(question: string, answer: string): Promise<void>;
    toggleProjectCompleted(id: string): Promise<void>;
    setProjectMapLocation(projectId: string, location: string): Promise<void>;
    getProjectMapLocations(): Promise<Array<[string, string]>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBill(bill: Bill, password: string): Promise<void>;
    updateClient(client: Client, password: string): Promise<void>;
    updatePayment(payment: Payment, password: string): Promise<void>;
    updateProject(project: Project, password: string): Promise<void>;
    updateUser(userPrincipal: Principal, profile: UserProfile): Promise<void>;
    validateActiveUser(email: string): Promise<void>;
    verifyHintAnswer(answer: string): Promise<string>;
}
import type { Bill as _Bill, BillFilters as _BillFilters, Client as _Client, ImportRequest as _ImportRequest, Payment as _Payment, PaymentFilters as _PaymentFilters, PaymentMode as _PaymentMode, Project as _Project, ProjectFilters as _ProjectFilters, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBill(arg0: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBill(to_candid_Bill_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBill(to_candid_Bill_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0);
            return result;
        }
    }
    async addPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_Payment_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_Payment_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0);
            return result;
        }
    }
    async addUser(arg0: UserProfile): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkDeleteBillsWithPassword(arg0: string, arg1: Array<BillKey>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteBillsWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteBillsWithPassword(arg0, arg1);
            return result;
        }
    }
    async bulkDeletePayments(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeletePayments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeletePayments(arg0, arg1);
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteBill(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteClient(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0, arg1);
            return result;
        }
    }
    async deletePayment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0, arg1);
            return result;
        }
    }
    async deleteProject(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0, arg1);
            return result;
        }
    }
    async deleteUsers(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUsers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUsers(arg0, arg1);
            return result;
        }
    }
    async filterBills(arg0: BillFilters): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBills(to_candid_BillFilters_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBills(to_candid_BillFilters_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterBillsByProject(arg0: string): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBillsByProject(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBillsByProject(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterPayments(arg0: PaymentFilters): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPayments(to_candid_PaymentFilters_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPayments(to_candid_PaymentFilters_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterProjects(arg0: ProjectFilters): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProjects(to_candid_ProjectFilters_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProjects(to_candid_ProjectFilters_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAdminPasswordQuestion(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPasswordQuestion();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPasswordQuestion();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjectNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectNames();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getBillDetails(arg0: string, arg1: string): Promise<Bill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillDetails(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillDetails(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getDefaultAdminProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultAdminProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultAdminProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGreetingMessage(arg0: null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGreetingMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGreetingMessage(arg0);
            return result;
        }
    }
    async getHintQuestion(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHintQuestion();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHintQuestion();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutstandingAmount(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutstandingAmount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutstandingAmount();
            return result;
        }
    }
    async getPaymentDetails(arg0: string): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentDetails(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentDetails(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectSummary(arg0: string): Promise<{
        outstanding: number;
        accountPayments: number;
        cashPayments: number;
        totalPayments: number;
        gstOutstanding: number;
        totalBills: number;
        project: Project;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectSummary(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectSummary(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectWiseAnalyticsData(arg0: string): Promise<Array<ProjectAnalyticsData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectWiseAnalyticsData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectWiseAnalyticsData(arg0);
            return result;
        }
    }
    async getSortedBills(arg0: string | null, arg1: boolean): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedBills(to_candid_opt_n41(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedBills(to_candid_opt_n41(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalGst(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalGst();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalGst();
            return result;
        }
    }
    async getUserAccess(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccess(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasActiveProfile(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasActiveProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasActiveProfile(arg0);
            return result;
        }
    }
    async hasProfileSetup(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProfileSetup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProfileSetup();
            return result;
        }
    }
    async importData(arg0: ImportRequest, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(to_candid_ImportRequest_n42(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(to_candid_ImportRequest_n42(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAdminPasswordSet(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminPasswordSet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminPasswordSet();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkMasterAdminPrincipal(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.linkMasterAdminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkMasterAdminPrincipal();
            return result;
        }
    }
    async linkUserByEmail(email: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.linkUserByEmail(email);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkUserByEmail(email);
            return result;
        }
    }
    async listUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async revealAdminPassword(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.revealAdminPassword(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revealAdminPassword(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setHintQuestionAndAnswer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHintQuestionAndAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHintQuestionAndAnswer(arg0, arg1);
            return result;
        }
    }
    async getCompletedProjectIds(): Promise<Array<string>> {
        return (await this.actor).getCompletedProjectIds();
    }
    async toggleProjectCompleted(id: string): Promise<void> {
        return (await this.actor).toggleProjectCompleted(id);
    }
    async setProjectMapLocation(projectId: string, location: string): Promise<void> {
        return (await this.actor).setProjectMapLocation(projectId, location);
    }
    async getProjectMapLocations(): Promise<Array<[string, string]>> {
        return (await this.actor).getProjectMapLocations();
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBill(arg0: Bill, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(to_candid_Bill_n8(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(to_candid_Bill_n8(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateClient(arg0: Client, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1);
            return result;
        }
    }
    async updatePayment(arg0: Payment, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(to_candid_Payment_n10(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(to_candid_Payment_n10(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateProject(arg0: Project, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1);
            return result;
        }
    }
    async updateUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validateActiveUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateActiveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateActiveUser(arg0);
            return result;
        }
    }
    async verifyHintAnswer(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyHintAnswer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyHintAnswer(arg0);
            return result;
        }
    }
}
function from_candid_Bill_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bill]): Bill | null {
    return value.length === 0 ? null : from_candid_Bill_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        outstanding: number;
        accountPayments: number;
        cashPayments: number;
        totalPayments: number;
        gstOutstanding: number;
        totalBills: number;
        project: _Project;
    }]): {
    outstanding: number;
    accountPayments: number;
    cashPayments: number;
    totalPayments: number;
    gstOutstanding: number;
    totalBills: number;
    project: Project;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    blockId: [] | [string];
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks: [] | [string];
}): {
    date: string;
    blockId?: string;
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks?: string;
} {
    return {
        date: value.date,
        blockId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.blockId)),
        unit: value.unit,
        description: value.description,
        projectId: value.projectId,
        includesGst: value.includesGst,
        billNumber: value.billNumber,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        amount: value.amount,
        remarks: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.remarks))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: _PaymentMode;
    amount: number;
    remarks: [] | [string];
}): {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: PaymentMode;
    amount: number;
    remarks?: string;
} {
    return {
        id: value.id,
        date: value.date,
        reference: value.reference,
        projectId: value.projectId,
        paymentMode: from_candid_PaymentMode_n29(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount,
        remarks: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.remarks))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    contact: string;
    accessProjects: Array<string>;
    role: _UserRole;
    fullName: string;
    email: string;
}): {
    active: boolean;
    contact: string;
    accessProjects: Array<string>;
    role: UserRole;
    fullName: string;
    email: string;
} {
    return {
        active: value.active,
        contact: value.contact,
        accessProjects: value.accessProjects,
        role: from_candid_UserRole_n37(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n35(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    account: null;
}): PaymentMode {
    return "cash" in value ? PaymentMode.cash : "account" in value ? PaymentMode.account : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n49(_uploadFile, _downloadFile, x));
}
function to_candid_BillFilters_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillFilters): _BillFilters {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Bill_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bill): _Bill {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ImportRequest_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportRequest): _ImportRequest {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentFilters_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentFilters): _PaymentFilters {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectFilters_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectFilters): _ProjectFilters {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: PaymentMode;
    amount: number;
    remarks?: string;
}): {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: _PaymentMode;
    amount: number;
    remarks: [] | [string];
} {
    return {
        id: value.id,
        date: value.date,
        reference: value.reference,
        projectId: value.projectId,
        paymentMode: to_candid_PaymentMode_n12(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount,
        remarks: value.remarks ? candid_some(value.remarks) : candid_none()
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    contact: string;
    accessProjects: Array<string>;
    role: UserRole;
    fullName: string;
    email: string;
}): {
    active: boolean;
    contact: string;
    accessProjects: Array<string>;
    role: _UserRole;
    fullName: string;
    email: string;
} {
    return {
        active: value.active,
        contact: value.contact,
        accessProjects: value.accessProjects,
        role: to_candid_UserRole_n16(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        email: value.email
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxAmount?: number;
    client?: string;
    minAmount?: number;
    blockId?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    includesGst?: boolean;
    billNumber?: string;
}): {
    maxAmount: [] | [number];
    client: [] | [string];
    minAmount: [] | [number];
    blockId: [] | [string];
    search: [] | [string];
    toDate: [] | [string];
    projectId: [] | [string];
    fromDate: [] | [string];
    includesGst: [] | [boolean];
    billNumber: [] | [string];
} {
    return {
        maxAmount: value.maxAmount ? candid_some(value.maxAmount) : candid_none(),
        client: value.client ? candid_some(value.client) : candid_none(),
        minAmount: value.minAmount ? candid_some(value.minAmount) : candid_none(),
        blockId: value.blockId ? candid_some(value.blockId) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        includesGst: value.includesGst ? candid_some(value.includesGst) : candid_none(),
        billNumber: value.billNumber ? candid_some(value.billNumber) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxAmount?: number;
    minAmount?: number;
    reference?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    paymentMode?: PaymentMode;
}): {
    maxAmount: [] | [number];
    minAmount: [] | [number];
    reference: [] | [string];
    search: [] | [string];
    toDate: [] | [string];
    projectId: [] | [string];
    fromDate: [] | [string];
    paymentMode: [] | [_PaymentMode];
} {
    return {
        maxAmount: value.maxAmount ? candid_some(value.maxAmount) : candid_none(),
        minAmount: value.minAmount ? candid_some(value.minAmount) : candid_none(),
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        paymentMode: value.paymentMode ? candid_some(to_candid_PaymentMode_n12(_uploadFile, _downloadFile, value.paymentMode)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client?: string;
    maxUnitPrice?: number;
    search?: string;
    toDate?: string;
    fromDate?: string;
    minUnitPrice?: number;
}): {
    client: [] | [string];
    maxUnitPrice: [] | [number];
    search: [] | [string];
    toDate: [] | [string];
    fromDate: [] | [string];
    minUnitPrice: [] | [number];
} {
    return {
        client: value.client ? candid_some(value.client) : candid_none(),
        maxUnitPrice: value.maxUnitPrice ? candid_some(value.maxUnitPrice) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        minUnitPrice: value.minUnitPrice ? candid_some(value.minUnitPrice) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectsData: Array<Project>;
    billsData: Array<Bill>;
    usersData: Array<[Principal, UserProfile]>;
    paymentsData: Array<Payment>;
    clientsData: Array<Client>;
}): {
    projectsData: Array<_Project>;
    billsData: Array<_Bill>;
    usersData: Array<[Principal, _UserProfile]>;
    paymentsData: Array<_Payment>;
    clientsData: Array<_Client>;
} {
    return {
        projectsData: value.projectsData,
        billsData: to_candid_vec_n44(_uploadFile, _downloadFile, value.billsData),
        usersData: to_candid_vec_n45(_uploadFile, _downloadFile, value.usersData),
        paymentsData: to_candid_vec_n47(_uploadFile, _downloadFile, value.paymentsData),
        clientsData: value.clientsData
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    blockId?: string;
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks?: string;
}): {
    date: string;
    blockId: [] | [string];
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks: [] | [string];
} {
    return {
        date: value.date,
        blockId: value.blockId ? candid_some(value.blockId) : candid_none(),
        unit: value.unit,
        description: value.description,
        projectId: value.projectId,
        includesGst: value.includesGst,
        billNumber: value.billNumber,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        amount: value.amount,
        remarks: value.remarks ? candid_some(value.remarks) : candid_none()
    };
}
function to_candid_tuple_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, UserProfile]): [Principal, _UserProfile] {
    return [
        value[0],
        to_candid_UserProfile_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    cash: null;
} | {
    account: null;
} {
    return value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.account ? {
        account: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Bill>): Array<_Bill> {
    return value.map((x)=>to_candid_Bill_n8(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, UserProfile]>): Array<[Principal, _UserProfile]> {
    return value.map((x)=>to_candid_tuple_n46(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Payment>): Array<_Payment> {
    return value.map((x)=>to_candid_Payment_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
