/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserFilters {
    contact?: string;
    name?: string;
    role?: UserRole;
    email?: string;
}
export interface BillKey {
    projectId: string;
    billNumber: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PaymentFilters {
    maxAmount?: number;
    minAmount?: number;
    reference?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    paymentMode?: PaymentMode;
}
export interface Payment {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: PaymentMode;
    amount: number;
    remarks?: string;
}
export interface BillFilters {
    maxAmount?: number;
    client?: string;
    minAmount?: number;
    blockId?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    includesGst?: boolean;
    billNumber?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ProjectFilters {
    client?: string;
    maxUnitPrice?: number;
    search?: string;
    toDate?: string;
    fromDate?: string;
    minUnitPrice?: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Bill {
    date: string;
    blockId?: string;
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks?: string;
}
export interface DashboardMetrics {
    outstanding: number;
    totalPayments: number;
    totalGst: number;
    totalBills: number;
}
export interface ProjectAnalyticsData {
    id: string;
    name: string;
    outstandingAmount: number;
}
export interface Project {
    id: string;
    client: string;
    endDate: string;
    name: string;
    address: string;
    notes: string;
    quantity: number;
    contactNumber: string;
    unitPrice: number;
    attachmentLinks: Array<string>;
    location: string;
    estimatedAmount: number;
    startDate: string;
}
export interface Client {
    id: string;
    contact: string;
    name: string;
    email: string;
    address: string;
    notes: string;
}
export interface UserProfile {
    active: boolean;
    contact: string;
    role: UserRole;
    fullName: string;
    email: string;
}
export enum PaymentMode {
    cash = "cash",
    account = "account"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addBill(bill: Bill): Promise<void>;
    addClient(client: Client): Promise<void>;
    addPayment(payment: Payment): Promise<void>;
    addProject(project: Project): Promise<void>;
    addUser(user: Principal, profile: UserProfile): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkDeleteBillsWithPassword(password: string, billKeys: Array<BillKey>): Promise<void>;
    bulkDeleteClients(password: string): Promise<void>;
    bulkDeletePayments(password: string, ids: Array<string>): Promise<void>;
    bulkDeleteProjects(password: string): Promise<void>;
    deleteBill(projectId: string, billNumber: string): Promise<void>;
    deleteClient(id: string): Promise<void>;
    deletePayment(id: string): Promise<void>;
    deleteProject(id: string): Promise<void>;
    deleteUser(user: Principal, password: string): Promise<void>;
    filterBills(billFilters: BillFilters): Promise<Array<Bill>>;
    filterBillsByProject(projectId: string): Promise<Array<Bill>>;
    filterPayments(filters: PaymentFilters): Promise<Array<Payment>>;
    filterProjects(filters: ProjectFilters): Promise<Array<Project>>;
    filterUsers(filters: UserFilters): Promise<Array<[Principal, UserProfile]>>;
    getAllBills(): Promise<Array<Bill>>;
    getAllClients(): Promise<Array<Client>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllProjectNames(): Promise<Array<string>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getGreetingMessage(arg0: null): Promise<string>;
    getOutstandingAmount(): Promise<number>;
    getProjectSummary(projectId: string): Promise<{
        outstanding: number;
        accountPayments: number;
        cashPayments: number;
        totalPayments: number;
        gstOutstanding: number;
        totalBills: number;
        project: Project;
    } | null>;
    getProjectWiseAnalyticsData(sortBy: string): Promise<Array<ProjectAnalyticsData>>;
    getSortedBills(sortBy: string | null, ascending: boolean): Promise<Array<Bill>>;
    getTotalGst(): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasActiveProfile(email: string): Promise<boolean>;
    hasProfileSetup(): Promise<boolean>;
    importActiveUsers(userProfilesData: Array<[Principal, UserProfile]>): Promise<void>;
    importBills(billsData: Array<Bill>): Promise<void>;
    importClients(clientsData: Array<Client>): Promise<void>;
    importPayments(paymentsData: Array<Payment>): Promise<void>;
    importProjects(projectsData: Array<Project>): Promise<void>;
    importUsers(usersData: Array<[Principal, UserProfile]>): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleUserActiveStatus(user: Principal, active: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBill(bill: Bill): Promise<void>;
    updateClient(client: Client): Promise<void>;
    updatePayment(payment: Payment): Promise<void>;
    updateProject(project: Project): Promise<void>;
    updateUser(user: Principal, profile: UserProfile): Promise<void>;
    validateActiveUser(email: string): Promise<void>;
}
import type { Bill as _Bill, BillFilters as _BillFilters, Payment as _Payment, PaymentFilters as _PaymentFilters, PaymentMode as _PaymentMode, Project as _Project, ProjectFilters as _ProjectFilters, UserFilters as _UserFilters, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBill(arg0: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBill(to_candid_Bill_n1(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBill(to_candid_Bill_n1(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async addClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0);
            return result;
        }
    }
    async addPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_Payment_n3(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_Payment_n3(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0);
            return result;
        }
    }
    async addUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, to_candid_UserProfile_n7(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, to_candid_UserProfile_n7(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async bulkDeleteBillsWithPassword(arg0: string, arg1: Array<BillKey>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteBillsWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteBillsWithPassword(arg0, arg1);
            return result;
        }
    }
    async bulkDeleteClients(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteClients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteClients(arg0);
            return result;
        }
    }
    async bulkDeletePayments(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeletePayments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeletePayments(arg0, arg1);
            return result;
        }
    }
    async bulkDeleteProjects(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteProjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteProjects(arg0);
            return result;
        }
    }
    async deleteBill(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0, arg1);
            return result;
        }
    }
    async deleteClient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deletePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return result;
        }
    }
    async filterBills(arg0: BillFilters): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBills(to_candid_BillFilters_n11(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBills(to_candid_BillFilters_n11(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async filterBillsByProject(arg0: string): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBillsByProject(arg0);
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBillsByProject(arg0);
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async filterPayments(arg0: PaymentFilters): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPayments(to_candid_PaymentFilters_n17(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPayments(to_candid_PaymentFilters_n17(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async filterProjects(arg0: ProjectFilters): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProjects(to_candid_ProjectFilters_n24(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProjects(to_candid_ProjectFilters_n24(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async filterUsers(arg0: UserFilters): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterUsers(to_candid_UserFilters_n26(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterUsers(to_candid_UserFilters_n26(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllProjectNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectNames();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getGreetingMessage(arg0: null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGreetingMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGreetingMessage(arg0);
            return result;
        }
    }
    async getOutstandingAmount(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutstandingAmount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutstandingAmount();
            return result;
        }
    }
    async getProjectSummary(arg0: string): Promise<{
        outstanding: number;
        accountPayments: number;
        cashPayments: number;
        totalPayments: number;
        gstOutstanding: number;
        totalBills: number;
        project: Project;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectSummary(arg0);
                return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectSummary(arg0);
            return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProjectWiseAnalyticsData(arg0: string): Promise<Array<ProjectAnalyticsData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectWiseAnalyticsData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectWiseAnalyticsData(arg0);
            return result;
        }
    }
    async getSortedBills(arg0: string | null, arg1: boolean): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedBills(to_candid_opt_n36(this.uploadFile, this.downloadFile, arg0), arg1);
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedBills(to_candid_opt_n36(this.uploadFile, this.downloadFile, arg0), arg1);
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTotalGst(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalGst();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalGst();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async hasActiveProfile(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasActiveProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasActiveProfile(arg0);
            return result;
        }
    }
    async hasProfileSetup(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProfileSetup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProfileSetup();
            return result;
        }
    }
    async importActiveUsers(arg0: Array<[Principal, UserProfile]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importActiveUsers(to_candid_vec_n37(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importActiveUsers(to_candid_vec_n37(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async importBills(arg0: Array<Bill>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importBills(to_candid_vec_n39(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importBills(to_candid_vec_n39(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async importClients(arg0: Array<Client>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importClients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importClients(arg0);
            return result;
        }
    }
    async importPayments(arg0: Array<Payment>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importPayments(to_candid_vec_n40(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importPayments(to_candid_vec_n40(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async importProjects(arg0: Array<Project>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importProjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importProjects(arg0);
            return result;
        }
    }
    async importUsers(arg0: Array<[Principal, UserProfile]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importUsers(to_candid_vec_n37(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importUsers(to_candid_vec_n37(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n7(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n7(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async toggleUserActiveStatus(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserActiveStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserActiveStatus(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBill(arg0: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(to_candid_Bill_n1(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(to_candid_Bill_n1(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateClient(arg0: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0);
            return result;
        }
    }
    async updatePayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(to_candid_Payment_n3(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(to_candid_Payment_n3(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0);
            return result;
        }
    }
    async updateUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_UserProfile_n7(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_UserProfile_n7(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async validateActiveUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateActiveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateActiveUser(arg0);
            return result;
        }
    }
}
function from_candid_Bill_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_PaymentMode_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n23(uploadFile, downloadFile, value);
}
function from_candid_Payment_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n21(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n31(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(uploadFile, downloadFile, value);
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n30(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        outstanding: number;
        accountPayments: number;
        cashPayments: number;
        totalPayments: number;
        gstOutstanding: number;
        totalBills: number;
        project: _Project;
    }]): {
    outstanding: number;
    accountPayments: number;
    cashPayments: number;
    totalPayments: number;
    gstOutstanding: number;
    totalBills: number;
    project: Project;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    blockId: [] | [string];
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks: [] | [string];
}): {
    date: string;
    blockId?: string;
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks?: string;
} {
    return {
        date: value.date,
        blockId: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.blockId)),
        unit: value.unit,
        description: value.description,
        projectId: value.projectId,
        includesGst: value.includesGst,
        billNumber: value.billNumber,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        amount: value.amount,
        remarks: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.remarks))
    };
}
function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: _PaymentMode;
    amount: number;
    remarks: [] | [string];
}): {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: PaymentMode;
    amount: number;
    remarks?: string;
} {
    return {
        id: value.id,
        date: value.date,
        reference: value.reference,
        projectId: value.projectId,
        paymentMode: from_candid_PaymentMode_n22(uploadFile, downloadFile, value.paymentMode),
        amount: value.amount,
        remarks: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.remarks))
    };
}
function from_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    contact: string;
    role: _UserRole;
    fullName: string;
    email: string;
}): {
    active: boolean;
    contact: string;
    role: UserRole;
    fullName: string;
    email: string;
} {
    return {
        active: value.active,
        contact: value.contact,
        role: from_candid_UserRole_n32(uploadFile, downloadFile, value.role),
        fullName: value.fullName,
        email: value.email
    };
}
function from_candid_tuple_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n30(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    account: null;
}): PaymentMode {
    return "cash" in value ? PaymentMode.cash : "account" in value ? PaymentMode.account : value;
}
function from_candid_variant_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n14(uploadFile, downloadFile, x));
}
function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n20(uploadFile, downloadFile, x));
}
function from_candid_vec_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n29(uploadFile, downloadFile, x));
}
function to_candid_BillFilters_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillFilters): _BillFilters {
    return to_candid_record_n12(uploadFile, downloadFile, value);
}
function to_candid_Bill_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bill): _Bill {
    return to_candid_record_n2(uploadFile, downloadFile, value);
}
function to_candid_PaymentFilters_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentFilters): _PaymentFilters {
    return to_candid_record_n18(uploadFile, downloadFile, value);
}
function to_candid_PaymentMode_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n6(uploadFile, downloadFile, value);
}
function to_candid_Payment_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n4(uploadFile, downloadFile, value);
}
function to_candid_ProjectFilters_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectFilters): _ProjectFilters {
    return to_candid_record_n25(uploadFile, downloadFile, value);
}
function to_candid_UserFilters_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserFilters): _UserFilters {
    return to_candid_record_n27(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n8(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(uploadFile, downloadFile, value);
}
function to_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxAmount?: number;
    client?: string;
    minAmount?: number;
    blockId?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    includesGst?: boolean;
    billNumber?: string;
}): {
    maxAmount: [] | [number];
    client: [] | [string];
    minAmount: [] | [number];
    blockId: [] | [string];
    search: [] | [string];
    toDate: [] | [string];
    projectId: [] | [string];
    fromDate: [] | [string];
    includesGst: [] | [boolean];
    billNumber: [] | [string];
} {
    return {
        maxAmount: value.maxAmount ? candid_some(value.maxAmount) : candid_none(),
        client: value.client ? candid_some(value.client) : candid_none(),
        minAmount: value.minAmount ? candid_some(value.minAmount) : candid_none(),
        blockId: value.blockId ? candid_some(value.blockId) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        includesGst: value.includesGst ? candid_some(value.includesGst) : candid_none(),
        billNumber: value.billNumber ? candid_some(value.billNumber) : candid_none()
    };
}
function to_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxAmount?: number;
    minAmount?: number;
    reference?: string;
    search?: string;
    toDate?: string;
    projectId?: string;
    fromDate?: string;
    paymentMode?: PaymentMode;
}): {
    maxAmount: [] | [number];
    minAmount: [] | [number];
    reference: [] | [string];
    search: [] | [string];
    toDate: [] | [string];
    projectId: [] | [string];
    fromDate: [] | [string];
    paymentMode: [] | [_PaymentMode];
} {
    return {
        maxAmount: value.maxAmount ? candid_some(value.maxAmount) : candid_none(),
        minAmount: value.minAmount ? candid_some(value.minAmount) : candid_none(),
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        paymentMode: value.paymentMode ? candid_some(to_candid_PaymentMode_n5(uploadFile, downloadFile, value.paymentMode)) : candid_none()
    };
}
function to_candid_record_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    blockId?: string;
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks?: string;
}): {
    date: string;
    blockId: [] | [string];
    unit: string;
    description: string;
    projectId: string;
    includesGst: boolean;
    billNumber: string;
    quantity: number;
    unitPrice: number;
    amount: number;
    remarks: [] | [string];
} {
    return {
        date: value.date,
        blockId: value.blockId ? candid_some(value.blockId) : candid_none(),
        unit: value.unit,
        description: value.description,
        projectId: value.projectId,
        includesGst: value.includesGst,
        billNumber: value.billNumber,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        amount: value.amount,
        remarks: value.remarks ? candid_some(value.remarks) : candid_none()
    };
}
function to_candid_record_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client?: string;
    maxUnitPrice?: number;
    search?: string;
    toDate?: string;
    fromDate?: string;
    minUnitPrice?: number;
}): {
    client: [] | [string];
    maxUnitPrice: [] | [number];
    search: [] | [string];
    toDate: [] | [string];
    fromDate: [] | [string];
    minUnitPrice: [] | [number];
} {
    return {
        client: value.client ? candid_some(value.client) : candid_none(),
        maxUnitPrice: value.maxUnitPrice ? candid_some(value.maxUnitPrice) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        minUnitPrice: value.minUnitPrice ? candid_some(value.minUnitPrice) : candid_none()
    };
}
function to_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact?: string;
    name?: string;
    role?: UserRole;
    email?: string;
}): {
    contact: [] | [string];
    name: [] | [string];
    role: [] | [_UserRole];
    email: [] | [string];
} {
    return {
        contact: value.contact ? candid_some(value.contact) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        role: value.role ? candid_some(to_candid_UserRole_n9(uploadFile, downloadFile, value.role)) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: PaymentMode;
    amount: number;
    remarks?: string;
}): {
    id: string;
    date: string;
    reference: string;
    projectId: string;
    paymentMode: _PaymentMode;
    amount: number;
    remarks: [] | [string];
} {
    return {
        id: value.id,
        date: value.date,
        reference: value.reference,
        projectId: value.projectId,
        paymentMode: to_candid_PaymentMode_n5(uploadFile, downloadFile, value.paymentMode),
        amount: value.amount,
        remarks: value.remarks ? candid_some(value.remarks) : candid_none()
    };
}
function to_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    contact: string;
    role: UserRole;
    fullName: string;
    email: string;
}): {
    active: boolean;
    contact: string;
    role: _UserRole;
    fullName: string;
    email: string;
} {
    return {
        active: value.active,
        contact: value.contact,
        role: to_candid_UserRole_n9(uploadFile, downloadFile, value.role),
        fullName: value.fullName,
        email: value.email
    };
}
function to_candid_tuple_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, UserProfile]): [Principal, _UserProfile] {
    return [
        value[0],
        to_candid_UserProfile_n7(uploadFile, downloadFile, value[1])
    ];
}
function to_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    cash: null;
} | {
    account: null;
} {
    return value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.account ? {
        account: null
    } : value;
}
function to_candid_vec_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, UserProfile]>): Array<[Principal, _UserProfile]> {
    return value.map((x)=>to_candid_tuple_n38(uploadFile, downloadFile, x));
}
function to_candid_vec_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Bill>): Array<_Bill> {
    return value.map((x)=>to_candid_Bill_n1(uploadFile, downloadFile, x));
}
function to_candid_vec_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Payment>): Array<_Payment> {
    return value.map((x)=>to_candid_Payment_n3(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
